version: '3.8'

services:
  suimilos-bot:
    build: .
    ports:
      - '4444:4444'
    environment:
      - PORT=4444
    env_file:
      - .env
    volumes:
      - ./indexed-data:/app/indexed-data
      - ./scripts/last-cursor.json:/app/scripts/last-cursor.json
    restart: unless-stopped
